name: Humanjournal
options:
  bundleIdPrefix: com.humanjournal
  deploymentTarget:
    iOS: "17.0"

targets:
  Humanjournal:
    type: application
    platform: iOS
    sources:
      - Humanjournal
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.humanjournal.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
